version: "3.9"
services:
  langgraph_app:
    image: langchain/langgraph-api:3.13
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
    command: >
      uvicorn serve:app --host 0.0.0.0 --port 8000 --log-config logging_config.py
