GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

# Test the healthcheck endpoint

GET http://127.0.0.1:8000/healthcheck
Accept: application/json

###

POST http://127.0.0.1:8000/chat
Content-Type: application/json

{
    "chat": "Hello"
}
